// The op-sequence runner — the Binding for taskstore/op-sequence@0 fixtures.
// Folds apply over ops from an empty store, resolves $-tokens in command
// inputs to live generated ids, and renders generated ids as their tokens
// in results: $k is the id generated by the k-th create returning created
// true (it-ts-model). Caller-supplied (imported) ids stay literal.

import { apply, emptyState, type Command, type StoreState } from "./core.js";

const ID_FIELDS = ["id", "dependsOn", "parent"] as const;

export function runOps(ops: Command[], initial?: StoreState): unknown[] {
  let state = initial ?? emptyState();
  const tokenToId = new Map<string, string>();
  const idToToken = new Map<string, string>();
  let nextToken = 1;

  const resolve = (v: unknown): unknown =>
    typeof v === "string" && tokenToId.has(v) ? tokenToId.get(v)! : v;

  const resolveOp = (op: Command): Command => {
    const out: Command = { ...op };
    for (const f of ID_FIELDS) if (f in out) out[f] = resolve(out[f]);
    if (Array.isArray(out.links))
      out.links = out.links.map((l) =>
        typeof l === "object" && l !== null
          ? { ...l, id: resolve((l as Record<string, unknown>).id), dependsOn: resolve((l as Record<string, unknown>).dependsOn) }
          : l,
      );
    return out;
  };

  const tokenize = (v: unknown): unknown => {
    if (typeof v === "string") return idToToken.get(v) ?? v;
    if (Array.isArray(v)) return v.map(tokenize);
    if (typeof v === "object" && v !== null)
      return Object.fromEntries(Object.entries(v).map(([k, val]) => [k, tokenize(val)]));
    return v;
  };

  const results: unknown[] = [];
  for (const op of ops) {
    const { result, state: next } = apply(state, resolveOp(op));
    state = next;
    if (result.created === true && typeof result.id === "string") {
      const token = `$${nextToken++}`;
      tokenToId.set(token, result.id);
      idToToken.set(result.id, token);
    }
    results.push(tokenize(result));
  }
  return results;
}
